name: CI

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        run: actions/setup-java@v2

      - name: Run tests
        run: |
          ./gradlew assembleDebug
