name: CI

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  run_detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.20

      - name: Run detekt
        run: detekt-cli --version

  run_all_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build SampleApplication
        run: |
          chmod +x ./gradlew
          ./gradlew test